### ISSUE TITLE
feat(NesButton): set icon color as well as text color

### ISSUE THREAD

**Issue by adil192** [erickzanardo/nes_ui#70]
**Description**

Currently, we have `lightLabelColor` and `darkLabelColor` in `NesButtonTheme`. However, this only affects the color of text and not the color of an `Icon`.
```dart
const NesButtonTheme({
  // ...
  required this.lightLabelColor,
  required this.darkLabelColor,
});
```

**Requirements**

- [ ] Set color of `Icon` widget
- [ ] Set colors of `NesIcon` widget

**Example**

The play icon should be white (i.e. matching the text) here:
<img src="https://github.com/erickzanardo/nes_ui/assets/21128619/981514b6-52c6-49d0-86fb-d037a4cd1634" width=300 alt="A dark green button with white text but a black icon">

**Additional Context**

I'm not sure how this would work with `NesIcon` since it requires both a primary and secondary color. Maybe the primary can be the same as the text color, and the secondary color could be the opposite of the text color (i.e. lightLabelColor vs darkLabelColor).
However, the regular `Icon` class should be straight forward to set the icon theme.

**Comment by adil192** [comment]
If I'm understanding correctly, does #72 only apply to material `Icon`s and not `NesIcon`s?

Currently I have to check the button type and manually change the NesIcon theme (primary and secondary colors) each time.

```dart
class _HomePageButton<T> extends StatelessWidget {
  // ...

  @override
  Widget build(BuildContext context) {
        // ...
        closedBuilder: (context, openContainer) => NesButton(
          child: Row(
            children: [
              NesIcon(
                iconData: icon,
                size: const Size.square(32),

                // TODO(adil192): remove after https://github.com/erickzanardo/nes_ui/issues/70
                primaryColor: switch (type) {
                  NesButtonType.primary => colorScheme.onPrimary,
                  _ => null,
                },
                secondaryColor: switch (type) {
                  NesButtonType.primary => colorScheme.primary,
                  _ => null,
                }
              ),
```

**Comment by erickzanardo** [comment]
Hey 👋

That is right. We can't apply the same approach for NesIcons because they have two colors, while material icons are a single one.

Maybe 'NesButtonTheme' could a include two new attributes, a lihhtIconColors and a darkIconColors, that would work similar to how the label color works?

Do you think that would cover your use case?

**Comment by adil192** [comment]
Yes that's probably more robust than my first suggestion

**Comment by erickzanardo** [comment]
Sounds good, gonna try to work on such feature in the following days

**Comment by adil192** [comment]
Would you like me to do this feature?

**Comment by erickzanardo** [comment]
> Would you like me to do this feature?

Hey, if you wanna give it a shoot, that would be awesome. I can try to help guiding if tou need advice.
