### ISSUE TITLE
refactor: Make icon static rather than NesIcons instance. 

### ISSUE THREAD

**Issue by eliasreis54** [erickzanardo/nes_ui#8]
**Description**

As a developer, I'd like to use the `NesIcons` class like I use `Icons` from Material: 

```
Icons.delete
```

Currently, I need to use `NesIcons.instance` to access any icon, I think we can change the `NesIcons` class and make the icons static rather than a `NesIcons` instance, so when I use an icon, that'll be: 

```
NesIcons.delete
```

What do you think? 

**Requirements**

- [x] There is no drop in test coverage.

**Comment by erickzanardo** [comment]
The way it is implemented right now, we can't make then static, all icons are late final fields, meaning that they are just instantiated when accessed. That makes it better memory usage, since only the used icons are allocated.

**Comment by adil192** [comment]
@erickzanardo Aren't static fields always `late`?
