### ISSUE TITLE
feat: add an video/ad icon

### ISSUE THREAD

**Issue by adil192** [erickzanardo/nes_ui#82]
**Description**

> Clearly describe what you are looking to add. The more context the better.

I'd like to ask if you could add a `NesIcons.instance.ad`. This could be similar to the gallery/window icon but with a play button inside.
I've just added [rewarded ads](https://support.google.com/admob/answer/7372450?hl=en) that let the player continue after dying by watching an ad. Currently, there's not a good NesIcon for this so I'm just using the shield (see the screenshot).

**Requirements**

- [x] Add an icon for a button that triggers an ad

**Additional Context**

> Add any other context or screenshots about the feature request go here.

<img src="https://github.com/erickzanardo/nes_ui/assets/21128619/aea1f0e7-54a4-4885-8f0f-24965652c961" width=300>

**Comment by erickzanardo** [comment]
Hey! You mean like an advertisement video icon, something that looks like that maybe?

<img width="286" alt="Screenshot 2023-09-22 at 09 25 56" src="https://github.com/erickzanardo/nes_ui/assets/835641/0d21b1f4-54db-458e-89e0-2f7b27c64d90">

**Comment by adil192** [comment]
Yes exactly!

**Comment by adil192** [comment]
That looks pretty good
Out of interest, how do you make these icons?

**Comment by erickzanardo** [comment]
You can use: https://minisprit.es

Just make sure to configure it to have a 8x8 grid, where the filled color
is black and the unfilled one white, and the background transparent, that
is the config that nes ui uses!

Then you can just copy and past the sprite code directly from the tool

Em sex., 22 de set. de 2023 às 10:10, Adil Hanney ***@***.***>
escreveu:
